export const SELLER_REGISTER_REQUEST = 'SELLER_REGISTER_REQUEST';
export const SELLER_REGISTER_SUCCESS = 'SELLER_REGISTER_SUCCESS';
export const SELLER_REGISTER_FAIL = 'SELLER_REGISTER_FAIL';

export const SELLER_BILLING_REQUEST = 'SELLER_BILLING_REQUEST';
export const SELLER_BILLING_SUCCESS = 'SELLER_BILLING_SUCCESS';
export const SELLER_BILLING_FAIL = 'SELLER_BILLING_FAIL';

export const SELLER_URL_SUCCESS = 'SELLER_URL_SUCCESS';
export const SELLER_URL_FAIL = 'SELLER_URL_FAIL';
export const SELLER_URL_REQUEST=  'SELLER_URL_REQUEST';